# Generated by Django 5.0.6 on 2024-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0002_alter_difbri_prof_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difbri_prof_user',
            name='photo',
            field=models.ImageField(default='profile.png', upload_to='imag/'),
        ),
    ]
