# Generated by Django 5.0.6 on 2024-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0003_alter_difbri_prof_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difbri_prof_user',
            name='photo',
            field=models.ImageField(default='imag/profile.png', upload_to='imag/'),
        ),
    ]
