# Generated by Django 5.0.6 on 2024-06-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0007_alter_difbri_photo_lenta_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difbri_photo_lenta',
            name='photo_lenta',
        ),
        migrations.AddField(
            model_name='difbri_photo_lenta',
            name='photos',
            field=models.ImageField(default='', upload_to='imag_lent/'),
        ),
        migrations.AlterField(
            model_name='difbri_photo_lenta',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Difbri.difbri_prof_user'),
        ),
    ]
