# Generated by Django 5.0.6 on 2024-06-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0005_difbri_photo_lenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difbri_photo_lenta',
            name='photo_lenta',
            field=models.ImageField(null=True, upload_to='imag_lent/'),
        ),
        migrations.AlterField(
            model_name='difbri_photo_lenta',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Difbri.difbri_prof_user'),
        ),
    ]
