# Generated by Django 5.0.6 on 2024-06-12 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0006_alter_difbri_photo_lenta_photo_lenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difbri_photo_lenta',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Difbri.difbri_prof_user'),
        ),
    ]
