# Generated by Django 5.0.6 on 2024-06-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0014_alter_difbri_friend_user1_alter_difbri_friend_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difbri_user_quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physics', 'Физика'), ('math', 'Математика'), ('chemistry', 'Химия'), ('engineering_drawing', 'Черчение'), ('english', 'Английский язык'), ('belarusian_language', 'Белорусский язык'), ('belarusian_literature', 'Белорусская литература'), ('russian_language', 'Русский язык'), ('russian_literature', 'Русская литература'), ('computer_science', 'Информатика'), ('geography', 'География'), ('world_history', 'Всемирная история'), ('history_of_belarus', 'История Беларуси'), ('social_studies', 'Обществознание'), ('biology', 'Биология')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('us_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_q', to='Difbri.difbri_prof_user')),
            ],
        ),
    ]
