# Generated by Django 5.0.6 on 2024-07-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0015_difbri_user_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('us_chat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us1', to='Difbri.difbri_prof_user')),
                ('us_chat2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us2', to='Difbri.difbri_prof_user')),
            ],
        ),
    ]
