# Generated by Django 5.0.6 on 2024-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0016_chat_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_mess',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
