# Generated by Django 5.0.6 on 2024-07-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0017_alter_chat_mess_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difbri_friend',
        ),
    ]
