# Generated by Django 5.0.6 on 2024-07-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0018_delete_difbri_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='otvet_vopr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.TextField(default='')),
                ('us_utvet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usotvet', to='Difbri.difbri_prof_user')),
                ('vopr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otvet', to='Difbri.difbri_user_quest')),
            ],
        ),
    ]
