# Generated by Django 5.0.6 on 2024-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Difbri', '0019_otvet_vopr'),
    ]

    operations = [
        migrations.AddField(
            model_name='otvet_vopr',
            name='kol_ot',
            field=models.IntegerField(default=0),
        ),
    ]
